import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{addPropertyControls,ControlType,motion}from"framer";import{containerStyles}from"https://framer.com/m/framer/default-utils.js@^0.45.0";import{useMemo}from"react";import{emptyStateStyle,stateParagraphStyle,stateTitleStyle}from"https://framer.com/m/framer/integrations-styles.js@^0.2.0";const BADGES={featured:"featured.svg",top:"top-post-badge.svg",review:"review.svg"};const productHuntRegex=/^https?:\/\/(?:www\.)?producthunt\.com\/posts\/([^\/]*)/;/**
 * PRODUCT HUNT
 *
 * @framerIntrinsicWidth 250
 * @framerIntrinsicHeight 54
 *
 * @framerSupportedLayoutWidth auto
 * @framerSupportedLayoutHeight auto
 */ export default function ProductHunt({url,type,theme,style,...props}){const badgeUrl=useMemo(()=>{var ref;const[,id]=(ref=url.match(productHuntRegex))!==null&&ref!==void 0?ref:[null,""];if(!id)return null;return`https://api.producthunt.com/widgets/embed-image/v1/${BADGES[type]}?post_id=${id}&theme=${theme}`;},[url,type,theme]);return(/*#__PURE__*/ _jsx(motion.div,{style:{...style,...containerStyles,placeContent:"center",placeItems:"center",overflow:"hidden"},...props,children:badgeUrl?/*#__PURE__*/ _jsx(motion.a,{href:url,target:"_blank",style:{...style,width:250,height:54},...props,children:/*#__PURE__*/ _jsx("img",{src:badgeUrl,alt:"Product Hunt Badge",width:"250",height:"54"})}):/*#__PURE__*/ _jsxs(motion.div,{style:{...emptyStateStyle,...style},...props,children:[/*#__PURE__*/ _jsx("h1",{style:stateTitleStyle,children:"Product Hunt"}),/*#__PURE__*/ _jsx("p",{style:stateParagraphStyle,children:"Set a product URL in the Properties."})]})}));};addPropertyControls(ProductHunt,{url:{type:ControlType.String,title:"URL",placeholder:"https://www.producthunt.com/posts/***",defaultValue:"https://www.producthunt.com/posts/framer-for-web"},type:{type:ControlType.Enum,title:"Type",options:["featured","top","review"],optionTitles:["Featured","Top Post Daily","Leave a Review"],defaultValue:"featured"},theme:{type:ControlType.Enum,options:["light","dark"],optionTitles:["Light","Dark"],displaySegmentedControl:true}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"ProductHunt","slots":[],"annotations":{"framerSupportedLayoutWidth":"auto","framerIntrinsicHeight":"54","framerContractVersion":"1","framerIntrinsicWidth":"250","framerSupportedLayoutHeight":"auto"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./ProductHunt.map